name: CI Build & Deploy opengenes MCP Server

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SERVER: ${{ secrets.EC2_HOST }}

    steps:
      - name: Checkout Opengenes MCP repo
        uses: actions/checkout@v3
        with:
          repository: iteleshov/opengenes-mcp

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push Docker Image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/opengenes-mcp-server:latest .
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/opengenes-mcp-server:latest

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-agent bash -c 'echo "SSH agent started" && ssh-add ~/.ssh/id_rsa'
          ssh-keyscan -H $SERVER >> ~/.ssh/known_hosts

      - name: Pull latest image opengenes-mcp-server
        run: |
          ssh ubuntu@$SERVER "docker compose pull opengenes-mcp-server"

      - name: Deploy container
        run: |
          ssh ubuntu@$SERVER "docker compose up -d opengenes-mcp-server --force-recreate"
